<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close this windowNew Account Business AccountRe</name>
   <tag></tag>
   <elementGuidId>0b5b043f-5de4-43f0-98a1-4bde49e1f2be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing needs your attention right now. Check back later.'])[1]/following::div[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel slds-modal slds-fade-in-open</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>title_305:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>content_305:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>320:0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close this windowNew Account: Business AccountReview the errors on this page.These required fields must be completed: Account Name, City, Office ID, Office Phone, State, ZipAccount InformationOffice ID*Complete this fieldStatus*In ProgressAccount Name*Complete this fieldDate Conversion BRIGHTDate PickerParent AccountShow More ▾Office Phone*Complete this fieldAccount Type*ResidentialView all dependenciesOffice EmailCompany TypeBranch OfficeView all dependenciesFaxTrading AsPINShareholder/Stakeholder Board--None--WebsiteMDS Status--None--NRDS IDMRIS CS Shareholder IDMRIS Office KeyMRIS CS AccountTypeRole IDAccount OwnerLevel 3MRIS CS Office Role IDTop100 OfficeTop 100 account checkbox for userMRIS CS Company TypeRole IDAccount_CSC Owner--None--MRIS CS Company Office KeyLead To Listing Agent--None--Server Access ToolsSyndication Terms of UseOther Server Access ToolsSyndication Terms of  Use InfoPrimary Service Jurisdiction--None--Broker Lead EmailSecondary Service Jurisdiction--None--Broker Lead PhoneImport Source IDOffice License NumberAgent CountOffice License Expiration DateDate PickerBroker CountImport IDImport SourceImport Source StatusDescription InformationDescriptionConversion FieldsConversion DateDate PickerOnboarding Deployment GroupConversion Preview DateDate PickerConversion Production DateDate PickerConversion Source MLSTREND FieldsTREND_Office_Number__cTREND Association IDBRIGHT FieldsBRIGHT_IsConvertedBRIGHT CS Office Role IDBRIGHT CS Account Type Role IDBRIGHT CS Shareholder IDBRIGHT CS Company Office KeyBRIGHT Office KeyBRIGHT CS Company Type Role IDRETS FieldsAuthorized UsePress Ctrl (Cmd on Mac) + Left Arrow or Ctrl (Cmd on Mac) + Right Arrow to move items between lists.AvailableAnalyticsBroker Back OfficeBroker OnlyCMACORECustomFormsIDXLockboxPremium ProductSyndicationVirtual Tour VendorVOWMove selection to ChosenMove selection to AvailableChosenBilling Type--None--Data Feed TypePress Ctrl (Cmd on Mac) + Left Arrow or Ctrl (Cmd on Mac) + Right Arrow to move items between lists.AvailableCORECustomIDXMove selection to ChosenMove selection to AvailableChosenRETS Billing ExclusionPress Ctrl (Cmd on Mac) + Left Arrow or Ctrl (Cmd on Mac) + Right Arrow to move items between lists.AvailableVendorBrokerageAgentMove selection to ChosenMove selection to AvailableChosenAdditional InformationNum Active Office Sec NCDate JoinedDate PickerNum Active SubsDate TerminatedDate PickerAddress InformationCopy Address to HomeSelect this and when the record is saved, all Mailing Address fields will be copied to corresponding Billing Address fields.Street NumberStreet NameHome Street NumberStreet TypeHome Street NameStreet Number SuffixHome Street TypeStreet DirectionHome Street Number SuffixUnit TypeHome Unit TypeUnit #Home Unit NumberAddl Display NameHome Addl Display NameZip*Complete this fieldHome ZipZip+4Home Zip+4City*Complete this fieldHome CityState*--None--Complete this fieldHome State--None--CountyHome CountyCountryHome CountryQAS Validation StatusPlease do not enter anything in this field.QAS Home Validation StatusPlease do not enter anything in this field.QAS Validation TimestampPlease do not enter anything in this field.DateDate PickerTimeTime PickerQAS Home Validation TimestampPlease do not enter anything in this field.DateDate PickerTimeTime PickerQAS Validation FootnotePlease do not enter anything in this fieldQAS Home Validation FootnotePlease do not enter anything in this fieldQAS_SectionPOBoxHome POBoxQAS Mailing Record TypeQAS Home Record TypeCS_CountryUNITED STATES OF AMERICACS_CountyCS_Unit Type--None--CS_Street Direction--None--CS_Street Type--None--ErrorCancelSave &amp; NewSave</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop&quot;]/div[@class=&quot;desktop container forceStyle oneOne lafStandardLayoutContainer lafAppLayoutHost forceAccess forceStyle oneOne&quot;]/div[@class=&quot;DESKTOP uiContainerManager&quot;]/div[@class=&quot;DESKTOP uiModal--medium uiModal--recordActionWrapper uiModal forceModal open active&quot;]/div[@class=&quot;panel slds-modal slds-fade-in-open&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing needs your attention right now. Check back later.'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/following::div[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
